/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import modelo.SistemaEnvios;

/**
 *
 * @author Mauro
 */
public class VentanaMenuPrincipal extends javax.swing.JFrame {

    private final SistemaEnvios sistema;

    /**
     * Creates new form VentanaMenuPrincipal
     */
    public VentanaMenuPrincipal(SistemaEnvios sistema) {
        if (sistema == null) {
            throw new IllegalArgumentException("El sistema no puede ser null.");
        }
        initComponents();
        this.sistema = sistema;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBarPrincipal = new javax.swing.JMenuBar();
        menuDatos = new javax.swing.JMenu();
        itemClientes = new javax.swing.JMenuItem();
        itemFuncionarios = new javax.swing.JMenuItem();
        itemTarifas = new javax.swing.JMenuItem();
        menuPaquetes = new javax.swing.JMenu();
        itemIngresoPaquete = new javax.swing.JMenuItem();
        itemEnvio = new javax.swing.JMenuItem();
        itemRecepcion = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itemPaquetesPorEstado = new javax.swing.JMenuItem();
        itemConsultaCliente = new javax.swing.JMenuItem();
        itemLogTransacciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema de Envíos");

        menuDatos.setText("Datos");

        itemClientes.setText("Clientes");
        itemClientes.addActionListener(this::itemClientesActionPerformed);
        menuDatos.add(itemClientes);

        itemFuncionarios.setText("Funcionarios");
        itemFuncionarios.addActionListener(this::itemFuncionariosActionPerformed);
        menuDatos.add(itemFuncionarios);

        itemTarifas.setText("Tarifas");
        itemTarifas.addActionListener(this::itemTarifasActionPerformed);
        menuDatos.add(itemTarifas);

        menuBarPrincipal.add(menuDatos);

        menuPaquetes.setText("Paquetes");

        itemIngresoPaquete.setText("Ingreso");
        itemIngresoPaquete.addActionListener(this::itemIngresoPaqueteActionPerformed);
        menuPaquetes.add(itemIngresoPaquete);

        itemEnvio.setText("Envío");
        itemEnvio.addActionListener(this::itemEnvioActionPerformed);
        menuPaquetes.add(itemEnvio);

        itemRecepcion.setText("Recepción");
        itemRecepcion.addActionListener(this::itemRecepcionActionPerformed);
        menuPaquetes.add(itemRecepcion);

        menuBarPrincipal.add(menuPaquetes);

        menuReportes.setText("Reportes");

        itemPaquetesPorEstado.setText("Paquetes por estado");
        itemPaquetesPorEstado.addActionListener(this::itemPaquetesPorEstadoActionPerformed);
        menuReportes.add(itemPaquetesPorEstado);

        itemConsultaCliente.setText("Consulta por cliente");
        itemConsultaCliente.addActionListener(this::itemConsultaClienteActionPerformed);
        menuReportes.add(itemConsultaCliente);

        itemLogTransacciones.setText("Log de transacciones");
        itemLogTransacciones.addActionListener(this::itemLogTransaccionesActionPerformed);
        menuReportes.add(itemLogTransacciones);

        menuBarPrincipal.add(menuReportes);

        setJMenuBar(menuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirVentana(javax.swing.JFrame ventana) {
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }

    private void itemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClientesActionPerformed
        abrirVentana(new VentanaClientes(sistema));
    }//GEN-LAST:event_itemClientesActionPerformed

    private void itemIngresoPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIngresoPaqueteActionPerformed
        abrirVentana(new VentanaIngresoPaquete(sistema));
    }//GEN-LAST:event_itemIngresoPaqueteActionPerformed

    private void itemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFuncionariosActionPerformed
        abrirVentana(new VentanaFuncionarios(sistema));
    }//GEN-LAST:event_itemFuncionariosActionPerformed

    private void itemTarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTarifasActionPerformed
        abrirVentana(new VentanaTarifas(sistema));
    }//GEN-LAST:event_itemTarifasActionPerformed

    private void itemEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEnvioActionPerformed
        abrirVentana(new VentanaEnvio(sistema));
    }//GEN-LAST:event_itemEnvioActionPerformed

    private void itemRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRecepcionActionPerformed
        abrirVentana(new VentanaRecepcion(sistema));
    }//GEN-LAST:event_itemRecepcionActionPerformed

    private void itemPaquetesPorEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPaquetesPorEstadoActionPerformed
        abrirVentana(new VentanaReportePaquetesPorEstado(sistema));
    }//GEN-LAST:event_itemPaquetesPorEstadoActionPerformed

    private void itemConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultaClienteActionPerformed
        abrirVentana(new VentanaConsultaCliente(sistema));
    }//GEN-LAST:event_itemConsultaClienteActionPerformed

    private void itemLogTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLogTransaccionesActionPerformed
        abrirVentana(new VentanaLogTransacciones(sistema));
    }//GEN-LAST:event_itemLogTransaccionesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemClientes;
    private javax.swing.JMenuItem itemConsultaCliente;
    private javax.swing.JMenuItem itemEnvio;
    private javax.swing.JMenuItem itemFuncionarios;
    private javax.swing.JMenuItem itemIngresoPaquete;
    private javax.swing.JMenuItem itemLogTransacciones;
    private javax.swing.JMenuItem itemPaquetesPorEstado;
    private javax.swing.JMenuItem itemRecepcion;
    private javax.swing.JMenuItem itemTarifas;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenu menuDatos;
    private javax.swing.JMenu menuPaquetes;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
}
